### ISSUE TITLE
Random HTTP 403 errors

### ISSUE THREAD

**Issue by sgruenheit** [prismicio/java-kit#46]
Hi guys!

We are experiencing random HTTP 403 errors when we are using the java-kit. It works for some time but then it starts to return 403 and keeps doing that until we create a new instance of the _Api_ class.

`java.lang.RuntimeException: HTTP error 403 ()
at io.prismic.core.HttpClient.fetch(HttpClient.java:76)
at io.prismic.Form$SearchForm.submit(Form.java:402)`

I'm wondering why this happens since no authentication is required for the endpoint.

Thanks in advance!

**Comment by srenault** [comment]
Hey @sgruenheit !

Yes, you shouldn't keep the `Api` instance between requests.
This is not related to authentication.
When querying some content, you specify a `ref` parameter. 
Each time you publish some content, this `ref` is updated. 
The `/api` endpoint that is represented by the `Api` class, gives the value of this ref (masterRef).
The be sure to have the last `ref`, a query is performed to this endpoint and another one is done to get back the content.

Is my explication understandable?
We are currently working on a new documentation that explains how our API works.

**Comment by sgruenheit** [comment]
Hi @srenault !

Ok, that explains a lot! I'm just used to keep an instance of an API in order to reduce overhead.

Thank you for your help!
